---
deployment:
  tasks:
    - export DEPLOYPATH=/home/titarmre/public_html
    - cp ./index.html $DEPLOYPATH
    - cp ./CSS/styles.css $DEPLOYPATH/CSS
    - cp ./HTML $DEPLOYPATH
    - cp ./JS/index.js $DEPLOYPATH/JS
