---
deployment:
  tasks:
    - export DEPLOYPATH=/home/titarmre/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp /CSS/* $DEPLOYPATH
    - /bin/cp /HTML/* $DEPLOYPATH
    - /bin/cp /Images/* $DEPLOYPATH
    - /bin/cp /JS/* $DEPLOYPATH
