---
deployment:
  tasks:
    - export DEPLOYPATH=/home/titarmre/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp /CSS/*.css $DEPLOYPATH
    - /bin/cp /HTML/*.html $DEPLOYPATH
    - /bin/cp /Images/* $DEPLOYPATH
    - /bin/cp /JS/*.js $DEPLOYPATH
